"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.OUTPUT = "output";
exports.CHANGE_GRAPH_NODE = "changeGraphNode";
exports.MAKE_GRAPH_CHOICE = "makeGraphChoice";
exports.CHANGE_GRAPH_PASSAGE = "changeGraphPassage";
exports.COMPLETE_GRAPH_NODE = "completeGraphNode";
exports.CHANGE_BAG_PASSAGE = "changeBagNode";
exports.COMPLETE_BAG_NODE = "completeBagNode";
exports.TRIGGERED_BAG_NODES = "triggeredBagNodes";
exports.RECEIVE_INPUT = "receiveInput";
exports.SET_VARIABLES = "setVariables";
exports.COMPLETE_PASSAGE = "completePassage";
